# Configurationg for Japanese pages (overrides _config.yml)
#
# To build Japanese page, specify --config option as follows:
# > jekyll build --config _config.yml,_config.en.yml

lang:        en

permalink:   /en/blog/:year/:month/:day/:title/
basedir:     /en/blog/

include:
  - .htaccess
  - index_en.md
  - 2_en.md

exclude:
  - _tmp
  - Gruntfile.js
  - package.json
  - node_modules
  - Gemfile
  - Gemfile.lock
  - vendor

  - _posts/ja
  - apollo
  - as
  - bakumatsu
  - css
  - hatebu_nenkan
  - hokkaido
  - illusion1
  - img
  - ipy
  - irb
  - ja/
  - javascript/application/*/*.md
  - javascript/*.md
  - marubiru
  - meltdown
  - misc

keep_files:
  - .git
  - apollo
  - as
  - bakumatsu
  - css
  - hatebu_nenkan
  - hokkaido
  - illusion1
  - img
  - ipy
  - irb
  - ja
  - javascript
  - marubiru
  - meltdown
  - misc
