safe:        false
lang:        [en, ja]
future:      false

markdown:    redcarpet
permalink:   /:categories/blog/:year/:month/:day/:title/

redcarpet:
  extensions:
    - autolink
    - tables

exclude:
  - _tmp
  - Gruntfile.js
  - package.json
  - node_modules
