# Configurationg for Japanese pages (overrides _config.yml)
#
# To build Japanese page, specify --config option as follows:
# > jekyll build --config _config.yml,_config.en.yml

lang:        en

permalink:   /en/blog/:year/:month/:day/:title/
basedir:     /en/blog/

exclude:
  - _tmp
  - Gruntfile.js
  - package.json
  - node_modules

  - _posts/ja
  - apollo
  - as
  - bakumatsu
  - css
  - hatebu_nenkan
  - hokkaido
  - illusion1
  - img
  - ipy
  - irb
  - ja
  - javascript
  - marubiru
  - meltdown
  - misc

keep_files:
  - .git
  - apollo
  - as
  - bakumatsu
  - css
  - hatebu_nenkan
  - hokkaido
  - illusion1
  - img
  - ipy
  - irb
  - ja
  - javascript
  - marubiru
  - meltdown
  - misc
