# Configurationg for Japanese pages (overrides _config.yml)
#
# To build Japanese page, specify --config option as follows:
# > jekyll build --config _config.yml,_config.ja.yml

lang:        ja
permalink:   /ja/blog/:year/:month/:day/:title/
basedir:     /ja/blog/

exclude:
  - _tmp
  - Gruntfile.js
  - package.json
  - node_modules

  - _posts/en
  - en

keep_files:
  - .git
  - en
