# Configurationg for Japanese pages (overrides _config.yml)
#
# To build Japanese page, specify --config option as follows:
# > jekyll build --config _config.yml,_config.ja.yml

lang:        ja
permalink:   /ja/blog/:year/:month/:day/:title/
basedir:     /ja/blog/

exclude:
  - javascript/application/ieerbug/index_en.md
  - javascript/application/racing/2_en.md

  - _tmp
  - Gruntfile.js
  - package.json
  - node_modules
  - Gemfile
  - Gemfile.lock
  - vendor

  - _posts/en
  - en

keep_files:
  - .git
  - en
  - javascript